### ISSUE TITLE
Audit assertPerformanceComplexity API

### ISSUE THREAD

**Issue by jsbean** [dn-m/PerformanceTesting#10]
First, I think we should keep the `linear` case under the same roof as all of the others, so that `assertConstantTimePerformance` is not a different public function. 

Instead, for now, we should do a `case let .constant = complexity { assertConstantTimePerformance(...) }`

With that said, I think we could clarify the path of types.

Perhaps we could rename this to:

```Swift
func assert(_ benchmark: Benchmark, isIn complexity: Complexity, minimumCorrelation: Double = 0.9)
```

**Comment by mossheim** [comment]
problem is that correlation is used to validate non-constant complexity, but slope is used to validate constant complexity. constant is a special case of linear with slope = 0.

**Comment by jsbean** [comment]
Ahh, that's fair. Will close until I have a better thought.

**Comment by mossheim** [comment]
eventually, i wanted to provide a convenience function that would wrap all of this up while hiding the slope and correlation parameters. so, just
```swift
func assert(_ benchmark: Benchmark, isIn complexity: Complexity)
```

then this would be possible

**Comment by jsbean** [comment]
Yes, I was wondering if `minimumCorrelation` needed to leak into the outside world!
