### ISSUE TITLE
Consider making Scale an enum which produces test points

### ISSUE THREAD

**Issue by jsbean** [dn-m/PerformanceTesting#13]
Right now, there is a slight dissonance to me regarding what a `Scale` is, and what `testPoints` are. They seem to be at two different levels of abstraction, seen from the viewpoint of the function call.

What if we implemented `Scale` as such:

```Swift
enum Scale {
    case tiny
    case small
    case medium
    case large
}

extension Scale {
    var testPoints: [Double] {
        switch self {
            case tiny:
                exponentialSeries(size: 10, from: 5, to: 100)
             ...
        }
    }
}
```

**Comment by jsbean** [comment]
Then, we could implement the following as such:

```Swift
    public func benchmark <C> (
        structure: C,
        setUp: SetUp<C>,
        trialCode: Run<C>,
        isMutating: Bool,
        scale: Scale = .medium,
        trialCount: Int = 10
    ) -> Benchmark
    {
        return scale.testPoints.map { testPoint in
            ...
        }
    }
```

**Comment by mossheim** [comment]
i understand that approach, but the point was to allow clients to define their own sets of test points if desired, and surface these as reasonable/common values to use. you're right that they're on different levels of abstraction, but i'd rather not constrain things here. `Scale` is really `ConvenienceTestPointSequence` in my mind.

**Comment by jsbean** [comment]
Cool! Maybe we can reopen after some more usage!
