### ISSUE TITLE
Do we need the testPoint (Double) in Run / Operation closure?

### ISSUE THREAD

**Issue by jsbean** [dn-m/PerformanceTesting#23]
It is used just a few times in `SetTests`, where it looks like it may be replaced with some other logic.

In trying to get rid of it, though, Swift gives me a very curious error at the location within the test:

> Cannot use mutating member on immutable value: 'array' is a 'let' constant

This error or only seems to occur if the type is `(inout Structure)`, but not `(inout Structure, Double)`.

**Comment by mossheim** [comment]
good question. when `O(f(n))` is a function of the number of elements, then it's generally not needed. But if it's a function of a numerical input or of a number of operations, then it's needed. A kind of simple but classic example would be establishing the time complexity of an algorithm that finds the nth Fibonacci number (which is `O(n)` in the input), or an algorithm that finds the factorial of n (again `O(n)`, or even `O(1)` with a lookup table).

**Comment by jsbean** [comment]
If it definitely is necessary, should we rename this to something like `size` (as, if I understand correctly, this is the size of the structure on which we are measuring the `operation`)?

**Comment by jsbean** [comment]
So, in the fib example, as that is a "structure-less" algorithm, should that have a different api anyway?

**Comment by jsbean** [comment]
By the way, I am getting _really_ interesting `EXC_BAD_ACCESS` errors now.

This may be a fun bug to track down and report.

**Comment by jsbean** [comment]
I'm gonna close this for now.
