### ISSUE TITLE
Naming of timeClosure and benchmarkClosure

### ISSUE THREAD

**Issue by jsbean** [dn-m/PerformanceTesting#9]
Both `time` and `benchmark` can be nouns / verbs, which can be a bit confusing.

Currently, they are being used as verbs, though they are functions with return values. Perhaps we can orient the names around the type of the return value, instead of what it takes to create that value.

**Comment by mossheim** [comment]
++ sgtm, any suggestions for names? `timedPerformance[Data]`?

**Comment by jsbean** [comment]
One strategy would be just to use the noun:

```Swift
func time <C> (testPoint: Double, structure: inout C, measuring closure: Run<C>) -> Double
```

```Swift
func benchmark <C> (
    structure: C,
    setUp: SetUp<C>,
    measuring closure: Run<C>,
    isMutating: Bool,
    testPoints: [Double] = Scale.medium,
    trialCount: Int = 10
) -> Benchmark
```

Then, the name is just describing (in noun form) what you get at the end.

**Comment by mossheim** [comment]
excellent! i like this.
